# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- task-canada.ca-container

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'ACRconnection'
    repository: 'track-web'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'